webtalk_init -webtalk_dir E:/class/Master of ANU/6213_Digital Systems and Microprocessors/my_6213/lab3/single_seven_segment_display/single_seven_segment_display.sim/sim_1/behav/xsim/xsim.dir/TEST_heartbeat_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Mar 19 11:46:03 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "48fc358f-df6a-4d70-ac5b-a5c1014b0dac" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8f672289c41d48ba8e1091456cc84357" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6472_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4087936607 -regid "" -xml E:/class/Master of ANU/6213_Digital Systems and Microprocessors/my_6213/lab3/single_seven_segment_display/single_seven_segment_display.sim/sim_1/behav/xsim/xsim.dir/TEST_heartbeat_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/class/Master of ANU/6213_Digital Systems and Microprocessors/my_6213/lab3/single_seven_segment_display/single_seven_segment_display.sim/sim_1/behav/xsim/xsim.dir/TEST_heartbeat_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/class/Master of ANU/6213_Digital Systems and Microprocessors/my_6213/lab3/single_seven_segment_display/single_seven_segment_display.sim/sim_1/behav/xsim/xsim.dir/TEST_heartbeat_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
